// File generated by FlutterFire CLI.
import 'package:ccquarters/environment.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return FirebaseOptions(
        apiKey: Environment.apiKeyWeb,
        appId: Environment.appIdWeb,
        messagingSenderId: Environment.messagingSenderIdWeb,
        projectId: Environment.projectId,
        authDomain: Environment.authDomain,
        databaseURL: Environment.databaseUrl,
        storageBucket: Environment.storageBucket,
        measurementId: Environment.measurementIdWeb,
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FirebaseOptions(
          apiKey: Environment.apiKeyMobile,
          appId: Environment.appIdMobile,
          messagingSenderId: Environment.messagingSenderIdMobile,
          projectId: Environment.projectId,
          databaseURL: Environment.databaseUrl,
          storageBucket: Environment.storageBucket,
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
