name: Pull request workflow

on:
  - pull_request
  - workflow_dispatch

jobs:
  test_flutter:
    uses: ./.github/workflows/test_flutter.yml

  try_build_proj:
    uses: ./.github/workflows/try_building_flutter.yml

  test_backend:
    uses: ./.github/workflows/test_backend.yml
    secrets: inherit
